buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: npm run dev -- --no-prod-url --local
responseHeaders:
  - pathPattern: .*en/location3.*
    headerKey: Content-Security-Policy
    headerValues:
      - font-src 'self'; font-src https://fonts.gstatic.com/